name: Deploy Theme to Dev
on:
  push:	
    branches:	
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: TryGhost/action-deploy-theme@v1.4.0
        with:
          api-url: ${{ secrets.DEV_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.DEV_GHOST_ADMIN_API_KEY }}
